export default [
  { id: 1, name: '3Mangos', patreonName: 'MongoArt', e621Name: '3mangos' },
  { id: 2, name: 'Aaron', patreonName: 'aaronarts', e621Name: 'aaron_(artist)' },
  { id: 3, name: 'Adam Wan', patreonName: 'zaush', e621Name: 'zaush' },
  { id: 4, name: 'Aggrobadger', patreonName: 'aggro_badger', e621Name: 'aggrobadger' },
  { id: 5, name: 'Ajin', patreonName: 'Ajin', e621Name: 'ajin' },
  {
    id: 6,
    name: 'Alabaster Tablespoon',
    patreonName: 'toomuchdynamite',
    e621Name: 'toomuchdynamite',
  },
  { id: 7, name: 'Angrboda', patreonName: null, e621Name: 'angrboda' },
  { id: 8, name: 'Anti-Dev', patreonName: 'anti_dev', e621Name: 'anti_dev' },
  { id: 9, name: 'Arbuzbudesh', patreonName: 'PriceForFreedom', e621Name: 'arbuzbudesh' },
  { id: 10, name: 'Arctic-Sekai', patreonName: null, e621Name: 'arctic-sekai' },
  { id: 11, name: 'Atryl', patreonName: 'atryl', e621Name: 'atryl' },
  { id: 12, name: 'AudioVideoMeow', patreonName: 'Audiovideomeow', e621Name: null },
  { id: 13, name: 'Azelyn', patreonName: 'AzelynArt', e621Name: 'azelyn' },
  { id: 14, name: 'Badshade', patreonName: 'BadShade', e621Name: 'shade_the_wolf' },
  { id: 15, name: 'Bakuhaku', patreonName: 'Bakuhaku', e621Name: 'bakuhaku' },
  { id: 16, name: 'Baraking', patreonName: null, e621Name: 'baraking' },
  { id: 17, name: 'Bastion', patreonName: 'BastionShadowpaw', e621Name: 'bastion' },
  { id: 18, name: 'Bear Hand', patreonName: null, e621Name: 'bear_hand' },
  { id: 19, name: 'Jeremy Bernal', patreonName: 'jbernal', e621Name: 'jeremy_bernal' },
  { id: 20, name: 'Black-Kitten', patreonName: 'blackkitten', e621Name: 'black-kitten' },
  { id: 21, name: 'BlitheDragon', patreonName: null, e621Name: 'blithedragon' },
  { id: 22, name: 'BNG', patreonName: null, e621Name: 'bng' },
  { id: 23, name: 'Bonk', patreonName: 'bonk', e621Name: 'bonk' },
  { id: 24, name: 'Braeburned', patreonName: 'braeburned', e621Name: 'braeburned' },
  { id: 25, name: 'Caninelove', patreonName: 'caninelove', e621Name: 'caninelove' },
  { id: 26, name: 'Cartoonlion', patreonName: null, e621Name: 'cartoonlion' },
  { id: 27, name: 'Castbound', patreonName: null, e621Name: 'castbound' },
  { id: 28, name: 'Celeste', patreonName: 'celeste', e621Name: 'celeste_(artist)' },
  {
    id: 29,
    name: 'The Secret Cave',
    patreonName: 'thesecretcave',
    e621Name: 'thesecretcave',
  },
  { id: 30, name: 'Chinpo', patreonName: 'powfooo', e621Name: 'chinpo  ' },
  { id: 31, name: 'Chochi', patreonName: null, e621Name: 'chochi' },
  { id: 32, name: 'Keishinkae', patreonName: 'keishinkae', e621Name: 'keishinkae' },
  { id: 33, name: 'Dark Penguin', patreonName: null, e621Name: 'darkpenguin' },
  { id: 34, name: 'Darkcandle', patreonName: null, e621Name: 'darkcandle' },
  { id: 35, name: 'Darknurse', patreonName: 'Dark_Nurse', e621Name: 'dark_nurse' },
  { id: 36, name: 'Darkzel', patreonName: null, e621Name: 'darkzel' },
  { id: 37, name: 'DBD', patreonName: 'dizzybydesign', e621Name: 'dbd' },
  { id: 38, name: 'Demicoeur', patreonName: 'demicoeur', e621Name: 'demicoeur' },
  { id: 39, name: 'Dmann', patreonName: null, e621Name: 'dmann892' },
  { id: 40, name: 'Domafox', patreonName: 'domafoxillustrations', e621Name: 'domafox' },
  { id: 41, name: 'Donryu', patreonName: null, e621Name: 'donryu' },
  { id: 42, name: 'Dosent', patreonName: 'Dosent', e621Name: 'dosent' },
  { id: 43, name: 'Dossun', patreonName: null, e621Name: 'dossun' },
  { id: 45, name: 'Draekos', patreonName: 'Draekos', e621Name: 'draekos' },
  { id: 46, name: 'Muskie', patreonName: 'muskie', e621Name: 'muskie' },
  { id: 47, name: 'Drenmar', patreonName: null, e621Name: 'drenmar' },
  { id: 48, name: 'DrGraevling', patreonName: 'drgraevling', e621Name: 'drgraevling' },
  { id: 49, name: 'Dysa', patreonName: 'fetalstar', e621Name: 'dysa' },
  {
    id: 50,
    name: 'Electrixocket',
    patreonName: 'electrixocketart',
    e621Name: 'electrixocket',
  },
  { id: 51, name: 'Eltonpot', patreonName: null, e621Name: 'eltonpot' },
  { id: 52, name: 'EWS', patreonName: 'ES_Productions', e621Name: 'eric_schwartz' },
  { id: 53, name: 'Fangdangler', patreonName: null, e621Name: 'fangdangler' },
  { id: 54, name: 'Fasttrack37d', patreonName: 'fasttrack', e621Name: 'fasttrack37d' },
  { id: 55, name: 'FearingFun', patreonName: 'FearingFun', e621Name: 'fearingfun' },
  { id: 56, name: 'Finir', patreonName: null, e621Name: 'finir' },
  { id: 57, name: 'Flanks', patreonName: null, e621Name: null },
  { id: 58, name: 'Fluff-Kevlar', patreonName: 'fluffkevlar', e621Name: 'fluff-kevlar' },
  { id: 59, name: 'Forge', patreonName: 'zeforge', e621Name: 'forge_(artist)' },
  { id: 60, name: 'KingTacoyaki', patreonName: 'KingTacoyaki', e621Name: 'tacoyaki' },
  { id: 61, name: 'Freckles', patreonName: 'Freckles', e621Name: 'freckles_(artist)' },
  { id: 62, name: 'Fred Perry', patreonName: 'bootydoc', e621Name: 'fred_perry' },
  {
    id: 63,
    name: 'Frisky Ferals',
    patreonName: 'FriskyFerals',
    e621Name: 'frisky_ferals',
  },
  { id: 65, name: 'Gillpanda', patreonName: 'Gillpanda', e621Name: 'gillpanda' },
  {
    id: 66,
    name: 'Giovanni',
    patreonName: 'GiovanniDaMilano',
    e621Name: 'kaisertaylorproducts',
  },
  { id: 67, name: 'Glitter-trap-boy', patreonName: null, e621Name: 'glitter_trap_boy' },
  { id: 68, name: 'Gnaw', patreonName: null, e621Name: 'gnaw' },
  { id: 69, name: 'Gunmouth', patreonName: 'gunmouth', e621Name: 'gunmouth' },
  {
    id: 70,
    name: 'Rockbottomfeeder',
    patreonName: 'rockbottomfeeder',
    e621Name: 'rockbottomfeeder',
  },
  { id: 71, name: 'Hardyboy', patreonName: 'Hardyboy', e621Name: 'hardyboy' },
  { id: 72, name: 'Harmarist', patreonName: null, e621Name: 'harmarist' },
  { id: 73, name: 'HerrAardy', patreonName: 'herraardy', e621Name: 'herr_aardy' },
  { id: 74, name: 'F-R95', patreonName: 'FR95', e621Name: 'f-r95' },
  { id: 75, name: 'Inoby', patreonName: null, e621Name: 'inoby' },
  { id: 76, name: 'Iudicium86', patreonName: null, e621Name: 'iudicium86' },
  { id: 77, name: 'Jackaloo', patreonName: 'Jackaloo', e621Name: 'jackaloo' },
  { id: 78, name: 'Jailbird', patreonName: null, e621Name: 'jailbird' },
  { id: 79, name: 'James Howard', patreonName: 'jameshoward', e621Name: 'james_howard' },
  {
    id: 80,
    name: 'Jonathan Ponikvar',
    patreonName: 'PeterAndWhitney',
    e621Name: 'peterandwhitney',
  },
  { id: 81, name: 'Kabier', patreonName: 'KabsCorner', e621Name: 'kabier' },
  { id: 82, name: 'Kadath', patreonName: 'Kadath', e621Name: 'kadath' },
  { id: 83, name: 'Kamicheetah', patreonName: null, e621Name: 'kamicheetah' },
  { id: 84, name: 'Keovi', patreonName: null, e621Name: 'keovi' },
  { id: 86, name: 'KinoJaggernov', patreonName: null, e621Name: 'kinojaggernov' },
  { id: 87, name: 'Kuroodod', patreonName: 'kuroodod', e621Name: 'kuroodod' },
  { id: 88, name: 'Leche', patreonName: null, e621Name: 'leche' },
  { id: 89, name: 'Leefuu', patreonName: 'leefuu', e621Name: 'leefuu' },
  { id: 90, name: 'Leobo', patreonName: 'Leoboart', e621Name: 'leobo' },
  { id: 91, name: 'Linno', patreonName: 'Gallygallo', e621Name: 'fabio_paulino' },
  { id: 92, name: 'Lizardlars', patreonName: 'Lizardlars', e621Name: 'lizardlars' },
  { id: 93, name: 'Vavacung', patreonName: 'vavacung', e621Name: 'vavacung' },
  { id: 94, name: 'Lumo', patreonName: 'pony_academy', e621Name: 'lumo' },
  { id: 95, name: 'Maririn', patreonName: 'user?u=4409499', e621Name: 'maririn' },
  {
    id: 97,
    name: 'Marik Azemus',
    patreonName: 'marikazemus',
    e621Name: 'marik_azemus34',
  },
  { id: 98, name: 'Markwulfgar', patreonName: 'markwulfgar', e621Name: 'markwulfgar' },
  { id: 99, name: 'Meesh', patreonName: 'meesh', e621Name: 'meesh' },
  { id: 100, name: 'Miles-DF', patreonName: 'mdf', e621Name: 'miles_df' },
  { id: 101, name: 'Miu', patreonName: 'luvpeaches', e621Name: 'miu' },
  { id: 102, name: 'Mizone', patreonName: null, e621Name: 'mizo_ne' },
  { id: 103, name: 'Mlpfwb', patreonName: 'Hapaloch', e621Name: 'aries84' },
  { id: 104, name: 'KamuDragon', patreonName: 'kamudragon', e621Name: 'kamudragon' },
  { id: 105, name: 'Mrbaton', patreonName: null, e621Name: 'mr_baton' },
  { id: 106, name: 'Naesyroc', patreonName: null, e621Name: 'naesyroc' },
  { id: 107, name: 'Narse', patreonName: null, e621Name: 'narse' },
  { id: 108, name: 'NaruEver', patreonName: 'lunateria', e621Name: 'naruever' },
  { id: 109, name: 'Nexus', patreonName: 'nexus_jubatus', e621Name: 'nexus' },
  { id: 110, name: 'Nicroze', patreonName: 'tokifuji', e621Name: 'nicroze ' },
  { id: 113, name: 'Ohmuu', patreonName: null, e621Name: 'ohmuu' },
  { id: 114, name: 'Oliver.lutro', patreonName: 'lutro', e621Name: 'oliver.lutro' },
  { id: 115, name: 'Onta', patreonName: 'ontasketch', e621Name: 'doxy' },
  { id: 116, name: 'Patto', patreonName: 'Patto', e621Name: 'patto' },
  { id: 117, name: 'Peritian', patreonName: 'peritian', e621Name: 'peritian' },
  { id: 118, name: 'Pokyuii', patreonName: 'pokyuii', e621Name: 'pokyuii' },
  { id: 119, name: 'Powfooo', patreonName: 'powfooo', e621Name: 'powfooo' },
  { id: 120, name: 'Pulsar', patreonName: 'pulsarbird', e621Name: 'pulsar' },
  { id: 121, name: 'Purplekecleon', patreonName: 'forbiddenflora', e621Name: null },
  { id: 122, name: 'Purplepardus', patreonName: 'milkymaiden', e621Name: 'purplepardus' },
  {
    id: 123,
    name: 'Purrnomagnum',
    patreonName: 'magsama',
    e621Name: 'purrnomagnum_(artist)',
  },
  { id: 124, name: 'Qualzar', patreonName: 'Qualzar', e621Name: 'qualzar' },
  { id: 125, name: 'Raghan', patreonName: 'Raghan', e621Name: 'raghan' },
  { id: 126, name: 'RatofDrawn', patreonName: 'RatofDrawn', e621Name: 'ratofdrawn' },
  { id: 127, name: 'REALLynxGirl', patreonName: 'lynxgirl', e621Name: 'reallynxgirl' },
  { id: 128, name: 'Redic-nomad', patreonName: null, e621Name: 'redic-nomad' },
  { id: 129, name: 'RedRusker', patreonName: 'redrusker', e621Name: 'redrusker' },
  { id: 130, name: 'Refer', patreonName: null, e621Name: 'refer' },
  { id: 131, name: 'Rinzy', patreonName: 'Rinzy', e621Name: 'rinzy' },
  { id: 132, name: 'Ritts', patreonName: 'Ritts', e621Name: 'ritts' },
  { id: 133, name: 'Roanoak', patreonName: 'pepperminthusky', e621Name: 'roanoak' },
  { id: 134, name: 'Rov', patreonName: 'Rov', e621Name: 'rov' },
  { id: 135, name: 'RrowdyBeast', patreonName: null, e621Name: 'rrowdybeast' },
  { id: 136, name: 'Roy Arashi', patreonName: 'RoyArashi', e621Name: 'roy_arashi' },
  { id: 137, name: 'Rukis', patreonName: 'Rukis', e621Name: 'rukis' },
  { id: 138, name: 'Ryoken', patreonName: null, e621Name: 'ryoken' },
  { id: 139, name: 'Ryukyur', patreonName: null, e621Name: 'ryukyur' },
  { id: 141, name: 'SayUncle', patreonName: null, e621Name: 'sayuncle' },
  { id: 142, name: 'Scappo', patreonName: 'Scappo', e621Name: 'Scappo' },
  { id: 143, name: 'Seth-Iova', patreonName: 'sethiova', e621Name: 'seth-iova' },
  { id: 144, name: 'Sethpup', patreonName: 'sethpup', e621Name: 'sethpup' },
  { id: 145, name: 'Shia', patreonName: 'cutecomics', e621Name: 'shia' },
  { id: 146, name: 'Shiuk', patreonName: 'Shiuk', e621Name: 'shiuk' },
  { id: 147, name: 'Sigil', patreonName: 'deervvitch', e621Name: 'deervvitch' },
  { id: 148, name: 'SigmaX', patreonName: 'SigmaX', e621Name: 'sigmax' },
  { id: 149, name: 'Siroc', patreonName: 'sirocistan', e621Name: 'siroc' },
  { id: 150, name: 'Skadjer', patreonName: null, e621Name: 'skadjer' },
  { id: 151, name: 'Skidd', patreonName: 'skidd', e621Name: 'skidd' },
  { id: 152, name: 'Slypon', patreonName: 'Slypon', e621Name: 'slypon' },
  { id: 153, name: 'Slyus', patreonName: null, e621Name: 'slyus ' },
  { id: 154, name: 'SmittyG', patreonName: 'SmittyG', e621Name: 'smitty_g' },
  { id: 155, name: 'Sollyz', patreonName: 'sollyz_sundyz', e621Name: 'sollyz' },
  {
    id: 156,
    name: 'Spelunker-Sal',
    patreonName: 'SpelunkerSal',
    e621Name: 'spelunker_sal',
  },
  { id: 157, name: 'Malachyte', patreonName: 'malachyte', e621Name: 'malachyte' },
  { id: 158, name: 'Staggard', patreonName: null, e621Name: 'staggard' },
  { id: 159, name: 'Stoopix', patreonName: null, e621Name: 'stoopix' },
  { id: 160, name: 'Strider Orion', patreonName: null, e621Name: null },
  { id: 161, name: 'Syynx', patreonName: 'syynx', e621Name: 'syynx' },
  { id: 162, name: 'Taen', patreonName: null, e621Name: 'taen' },
  { id: 163, name: 'Tanksi', patreonName: null, e621Name: 'tanks_(artist)' },
  {
    id: 164,
    name: 'TheBlackRook',
    patreonName: 'HolyKnightNadia',
    e621Name: 'theblackrook',
  },
  {
    id: 165,
    name: 'Thegeckoninja',
    patreonName: 'TheGeckoNinja',
    e621Name: 'thegeckoninja',
  },
  { id: 166, name: 'Thingsmart', patreonName: 'unDivine', e621Name: 'thingsmart' },
  { id: 167, name: 'Tokaido', patreonName: null, e621Name: 'tokaido' },
  { id: 168, name: 'Tokifuji', patreonName: 'tokifuji', e621Name: 'tokifuji' },
  { id: 169, name: 'Tolok', patreonName: null, e621Name: 'tolok' },
  { id: 170, name: 'Tsampikos', patreonName: 'Tsampikos', e621Name: 'tsampikos' },
  { id: 171, name: 'Twinkle-Sez', patreonName: 'Barathrum', e621Name: 'twinkle-sez' },
  { id: 172, name: 'Tygurstar', patreonName: 'INKtiger', e621Name: 'inktiger' },
  { id: 173, name: 'Vexxy', patreonName: null, e621Name: 'vexxy' },
  { id: 174, name: 'VU06', patreonName: null, e621Name: 'vu06' },
  { id: 175, name: 'Watsup', patreonName: 'watsup', e621Name: 'watsup' },
  { id: 176, name: 'WFA', patreonName: 'wfa', e621Name: 'wfa' },
  {
    id: 177,
    name: 'WMustang',
    patreonName: 'wolver_mustang',
    e621Name: 'wolver_mustang',
  },
  { id: 178, name: 'Wolfy-Nail', patreonName: null, e621Name: 'wolfy-nail' },
  { id: 179, name: 'X03', patreonName: null, e621Name: 'x03' },
  { id: 180, name: 'Zeiro', patreonName: null, e621Name: 'zeiro' },
  { id: 181, name: 'Zerofox1000', patreonName: null, e621Name: 'zerofox1000' },
  { id: 182, name: 'Zeta-Haru', patreonName: 'zetaharu', e621Name: 'zeta-haru' },
  { id: 183, name: 'Ziude', patreonName: null, e621Name: 'juano' },
  { id: 184, name: 'Zummeng', patreonName: 'Zummeng', e621Name: 'Zummeng' },
  {
    id: 186,
    name: 'Captain Nikko',
    patreonName: 'Nikkonator',
    e621Name: 'captain_nikko',
  },
  { id: 188, name: 'Hioshiru', patreonName: '9Tales', e621Name: 'hioshiru' },
  { id: 190, name: 'Suirano', patreonName: 'suirano', e621Name: 'suirano' },
  { id: 191, name: 'Boosterpang', patreonName: 'boosterpang', e621Name: 'boosterpang' },
  { id: 192, name: 'SimonAquarius', patreonName: null, e621Name: 'simonaquarius ' },
  { id: 193, name: 'Colt3n', patreonName: 'goodboycomics', e621Name: 'colt3n' },
  { id: 194, name: 'Somescrub', patreonName: null, e621Name: 'somescrub' },
  { id: 195, name: 'Neattea', patreonName: null, e621Name: 'neattea' },
  { id: 196, name: 'Jush', patreonName: 'SuperNsfwZhenya', e621Name: 'jush' },
  { id: 197, name: 'HolloNut', patreonName: null, e621Name: 'hollo_nut' },
  { id: 198, name: 'StrangerDanger', patreonName: null, e621Name: 'strangerdanger' },
  { id: 199, name: 'Anhes', patreonName: 'anhes', e621Name: null },
  {
    id: 200,
    name: 'Hobbes Maxwell',
    patreonName: 'Boiler3',
    e621Name: 'hobbes_maxwell ',
  },
  { id: 201, name: 'SalKitten', patreonName: 'Lewdbeans', e621Name: 'salkitten' },
  { id: 202, name: 'Ratcha', patreonName: 'ratcha', e621Name: 'ratcha' },
  {
    id: 203,
    name: 'Spelunker Sal',
    patreonName: 'SpelunkerSal',
    e621Name: 'spelunker_sal',
  },
  { id: 204, name: 'Matemi', patreonName: 'matemi', e621Name: 'matemi' },
  { id: 205, name: 'Hatton Slayden', patreonName: null, e621Name: 'hattonslayden' },
  { id: 206, name: '2tipsie4me', patreonName: null, e621Name: 'hot_headed_clover' },
  { id: 207, name: 'Saurian', patreonName: 'Saurian', e621Name: 'saurian_(artist)' },
  {
    id: 208,
    name: 'Basketgardevoir',
    patreonName: 'user?u=12272930',
    e621Name: 'alyrise',
  },
  { id: 209, name: 'Niro', patreonName: 'xnirox', e621Name: 'xnirox' },
  { id: 210, name: 'Asbel_Lhant', patreonName: 'Asbie', e621Name: 'asbel_lhant' },
  {
    id: 211,
    name: 'Rainbowflyer',
    patreonName: 'rainbowflyer',
    e621Name: 'rainbow-flyer',
  },
  { id: 212, name: 'Kayla-Na', patreonName: 'EbonyChimera', e621Name: 'ebonychimera' },
  { id: 213, name: 'San Ruishin', patreonName: null, e621Name: 'san_ruishin' },
  { id: 214, name: 'MrPloxy', patreonName: null, e621Name: 'masterploxy ' },
  { id: 215, name: 'Mykiio', patreonName: null, e621Name: 'mykiio' },
  { id: 216, name: 'Aogami', patreonName: null, e621Name: 'aogami ' },
  { id: 217, name: 'Shino', patreonName: 'Shino', e621Name: 'Shinodage' },
  {
    id: 218,
    name: 'KanashiiPanda',
    patreonName: 'kanashiipanda',
    e621Name: 'kanashiipanda',
  },
  { id: 219, name: 'Teckworks', patreonName: null, e621Name: null },
  { id: 220, name: 'zp92', patreonName: null, e621Name: null },
  { id: 221, name: 'Notorious', patreonName: null, e621Name: null },
  { id: 222, name: 'Sheer', patreonName: null, e621Name: null },
  { id: 223, name: 'Penlink', patreonName: null, e621Name: null },
  { id: 224, name: 'Pudding', patreonName: null, e621Name: null },
  { id: 225, name: 'CoraBlue', patreonName: 'corablue', e621Name: 'corablue' },
  { id: 226, name: 'Chococosalo', patreonName: null, e621Name: null },
  { id: 227, name: 'Candylady', patreonName: null, e621Name: null },
  { id: 228, name: 'Luckypan', patreonName: null, e621Name: null },
  { id: 229, name: 'Second City Saint', patreonName: null, e621Name: null },
  { id: 230, name: 'Tanraak', patreonName: null, e621Name: null },
  { id: 231, name: 'Amur', patreonName: null, e621Name: null },
  { id: 232, name: 'Nedoiko', patreonName: null, e621Name: null },
  { id: 233, name: 'SteelTigerWolf', patreonName: null, e621Name: null },
  { id: 234, name: 'Kryptchild', patreonName: null, e621Name: null },
  { id: 235, name: 'MeggChan', patreonName: null, e621Name: null },
  { id: 236, name: 'Spunkubus', patreonName: null, e621Name: null },
  { id: 237, name: 'SpaceDust', patreonName: null, e621Name: null },
  { id: 238, name: 'Cloudz', patreonName: null, e621Name: null },
  { id: 239, name: 'Alcor', patreonName: null, e621Name: null },
  { id: 240, name: 'Lunalei', patreonName: null, e621Name: null },
  { id: 241, name: 'Master Oki Akai', patreonName: null, e621Name: null },
  { id: 242, name: 'LDRaptor', patreonName: null, e621Name: null },
  { id: 243, name: 'Kathy-Lu', patreonName: null, e621Name: null },
  { id: 244, name: 'Tenaflux', patreonName: null, e621Name: null },
  { id: 245, name: 'KuroAme', patreonName: null, e621Name: null },
  { id: 246, name: 'Etuix', patreonName: null, e621Name: null },
  { id: 247, name: 'Artdecade', patreonName: null, e621Name: null },
  { id: 248, name: 'Thefuckingdevil', patreonName: 'GrimDevil', e621Name: null },
  { id: 249, name: 'Vader-San', patreonName: null, e621Name: null },
  { id: 251, name: '0Lightsource', patreonName: '0Lightsource', e621Name: null },
  { id: 253, name: 'Morpp', patreonName: null, e621Name: null },
  { id: 255, name: 'Hyhlion', patreonName: null, e621Name: null },
  { id: 257, name: 'dksk30', patreonName: null, e621Name: null },
  {
    id: 259,
    name: 'Abluedeer',
    patreonName: 'dark_blue_workshop',
    e621Name: 'abluedeer',
  },
  { id: 260, name: 'TheWyvernsWeaver', patreonName: null, e621Name: null },
  { id: 261, name: 'Kaylee', patreonName: null, e621Name: null },
  { id: 262, name: 'Max Blackrabbit', patreonName: null, e621Name: null },
  { id: 263, name: 'Blackmailz', patreonName: null, e621Name: null },
  { id: 264, name: 'Akazulla', patreonName: null, e621Name: null },
  { id: 265, name: 'Philip M Jackson', patreonName: null, e621Name: null },
  { id: 266, name: 'RamTheDragon', patreonName: null, e621Name: null },
  { id: 267, name: 'Akiric', patreonName: null, e621Name: null },
  { id: 268, name: 'Jagon', patreonName: null, e621Name: null },
  { id: 269, name: 'Feretta', patreonName: null, e621Name: null },
  { id: 270, name: 'Teil', patreonName: null, e621Name: null },
  { id: 271, name: 'ThunderousErections', patreonName: null, e621Name: null },
  { id: 272, name: 'Meraence', patreonName: null, e621Name: null },
  { id: 273, name: 'Wemd', patreonName: null, e621Name: null },
  { id: 274, name: 'Myure', patreonName: null, e621Name: null },
  { id: 278, name: 'Xpray', patreonName: 'Xpray', e621Name: null },
  { id: 279, name: 'Raus', patreonName: 'raus', e621Name: null },
  { id: 280, name: 'Pumperbear', patreonName: 'Pumperbear', e621Name: null },
  { id: 281, name: 'Blattarieva', patreonName: null, e621Name: null },
  { id: 282, name: 'Stboogie', patreonName: null, e621Name: null },
  { id: 283, name: 'Echoseed', patreonName: null, e621Name: null },
  { id: 284, name: 'Rinfu', patreonName: null, e621Name: null },
  { id: 285, name: 'Bouchee', patreonName: 'Lagotrope', e621Name: 'lagotrope' },
  { id: 286, name: 'KyotoKisha15', patreonName: null, e621Name: null },
  { id: 287, name: 'Fluke', patreonName: null, e621Name: null },
  { id: 288, name: 'SydneySnake', patreonName: null, e621Name: null },
  { id: 289, name: 'Blitzdrachin', patreonName: 'sifyro', e621Name: null },
  { id: 290, name: 'Baaleze', patreonName: null, e621Name: null },
  { id: 291, name: 'Iskra', patreonName: 'iskra', e621Name: 'iskra' },
  { id: 292, name: 'Llllore', patreonName: null, e621Name: null },
  { id: 293, name: 'Douglas Kim', patreonName: 'douglaskim', e621Name: 'douglas_kim' },
  { id: 294, name: 'Tycloud', patreonName: null, e621Name: null },
  { id: 295, name: 'DryChicken', patreonName: null, e621Name: null },
  { id: 296, name: 'Edesk', patreonName: null, e621Name: null },
  { id: 297, name: 'Cap.Grolarbear', patreonName: null, e621Name: null },
  { id: 298, name: 'Ackanime', patreonName: null, e621Name: null },
  { id: 299, name: 'Sefeiren', patreonName: null, e621Name: null },
  { id: 302, name: 'Jay Naylor', patreonName: null, e621Name: null },
  { id: 303, name: 'SlowFag', patreonName: null, e621Name: null },
  { id: 304, name: 'Ripperelite', patreonName: null, e621Name: null },
  { id: 305, name: 'RhoArt', patreonName: null, e621Name: null },
  { id: 306, name: 'Azaleesh', patreonName: null, e621Name: null },
  { id: 307, name: 'DarkMirage', patreonName: null, e621Name: null },
  { id: 308, name: 'LobaDeLaLuna', patreonName: null, e621Name: null },
  { id: 309, name: 'Hornedfreak', patreonName: null, e621Name: null },
  { id: 310, name: 'Fuf', patreonName: 'Fufology', e621Name: 'fuf' },
  { id: 313, name: 'Furball', patreonName: null, e621Name: null },
  { id: 314, name: 'RupaLulu', patreonName: null, e621Name: null },
  { id: 315, name: 'Nihaotomita', patreonName: null, e621Name: null },
  { id: 316, name: 'Koorinezumi', patreonName: null, e621Name: null },
  { id: 317, name: 'Tailshigh', patreonName: null, e621Name: null },
  { id: 318, name: 'Xxgato', patreonName: null, e621Name: null },
  { id: 319, name: 'DelKon', patreonName: null, e621Name: null },
  { id: 320, name: 'Brushfire', patreonName: null, e621Name: null },
  { id: 321, name: 'Rayka', patreonName: null, e621Name: null },
  { id: 322, name: 'BassyWolfeh', patreonName: null, e621Name: null },
  { id: 323, name: 'Kevinsano', patreonName: null, e621Name: null },
  { id: 324, name: 'Zero-Sum', patreonName: null, e621Name: null },
  { id: 325, name: 'AriesArtist', patreonName: null, e621Name: null },
  { id: 326, name: 'ClaraLaine', patreonName: null, e621Name: null },
  { id: 327, name: 'DarkViolet', patreonName: null, e621Name: null },
  { id: 328, name: 'Elfein', patreonName: 'Elfein', e621Name: 'elfein' },
  { id: 329, name: 'LilyBird', patreonName: null, e621Name: null },
  { id: 330, name: 'Sonicboom53', patreonName: null, e621Name: null },
  { id: 332, name: 'Vulapa', patreonName: null, e621Name: null },
  { id: 333, name: 'Kekitopu', patreonName: null, e621Name: null },
  { id: 334, name: 'Ruaidri', patreonName: null, e621Name: null },
  { id: 335, name: 'Palcomix', patreonName: null, e621Name: null },
  { id: 336, name: 'Spirale', patreonName: null, e621Name: null },
  { id: 337, name: 'Redemption3445', patreonName: null, e621Name: null },
  { id: 338, name: 'MisterStallion', patreonName: 'MisterStallion', e621Name: null },
  { id: 340, name: 'Caribou', patreonName: null, e621Name: null },
  { id: 341, name: 'Whygena', patreonName: null, e621Name: null },
  { id: 342, name: 'Falcon McCooper', patreonName: 'purplebirdman', e621Name: null },
  { id: 343, name: 'Mamabliss', patreonName: null, e621Name: null },
  { id: 344, name: 'DinamiteCupcake', patreonName: null, e621Name: null },
  { id: 345, name: 'Caustic Crayon', patreonName: null, e621Name: null },
  { id: 346, name: 'Kemotsubo', patreonName: null, e621Name: null },
  { id: 347, name: 'Monogg', patreonName: null, e621Name: null },
  { id: 348, name: 'CaptainZepto', patreonName: null, e621Name: null },
  { id: 349, name: 'JAEH', patreonName: null, e621Name: null },
  { id: 350, name: 'Brandon Zuckermann', patreonName: null, e621Name: null },
  { id: 351, name: 'Anubis-kruger', patreonName: null, e621Name: null },
  { id: 352, name: 'Funkybun', patreonName: 'funkybun', e621Name: 'funkybun' },
  { id: 353, name: 'GrimArt', patreonName: 'grimart', e621Name: 'grimart' },
  { id: 354, name: 'Shortwings', patreonName: null, e621Name: null },
  { id: 355, name: 'Heather Bruton', patreonName: null, e621Name: null },
  { id: 356, name: 'Danza', patreonName: null, e621Name: null },
  { id: 357, name: 'Piyotm', patreonName: null, e621Name: null },
  { id: 358, name: 'Chris McKinley', patreonName: null, e621Name: null },
  { id: 359, name: 'Arh', patreonName: null, e621Name: null },
  { id: 360, name: 'Viktria', patreonName: null, e621Name: null },
  { id: 361, name: 'GeminiSaint', patreonName: null, e621Name: null },
  { id: 362, name: 'Emikochan', patreonName: null, e621Name: null },
  { id: 363, name: 'iGinger', patreonName: null, e621Name: null },
  { id: 364, name: 'Proxer', patreonName: null, e621Name: null },
  { id: 365, name: 'Regolith Art', patreonName: null, e621Name: null },
  { id: 367, name: 'Foxxx321', patreonName: null, e621Name: null },
  { id: 368, name: 'Elvche', patreonName: null, e621Name: null },
  { id: 371, name: 'The_Weaver', patreonName: null, e621Name: null },
  { id: 372, name: 'Fuzzy-Britches', patreonName: null, e621Name: 'fuzzy-britches' },
  { id: 373, name: 'Glopossum', patreonName: 'glopossum', e621Name: null },
  { id: 374, name: 'Backlash91', patreonName: null, e621Name: null },
  { id: 375, name: 'Felino', patreonName: 'Felino', e621Name: 'felino' },
  { id: 376, name: 'Inuyuru', patreonName: null, e621Name: null },
  { id: 377, name: 'Polygon5', patreonName: null, e621Name: null },
  { id: 378, name: 'honukuko', patreonName: null, e621Name: null },
  { id: 379, name: 'Anaugi', patreonName: null, e621Name: null },
  { id: 380, name: 'Bunnybits', patreonName: null, e621Name: null },
  { id: 382, name: 'Yumei', patreonName: null, e621Name: null },
  { id: 383, name: 'Woofypaws', patreonName: null, e621Name: 'woofyrainshadow' },
  { id: 384, name: 'Xierra099', patreonName: null, e621Name: null },
  { id: 385, name: 'Rob Civecat', patreonName: null, e621Name: null },
  { id: 386, name: 'Atrolux', patreonName: null, e621Name: 'atrolux' },
  { id: 387, name: 'Compfive', patreonName: null, e621Name: null },
  { id: 388, name: 'Pedverse', patreonName: null, e621Name: null },
  { id: 389, name: 'Pizzie', patreonName: null, e621Name: null },
  { id: 390, name: 'Wyldfire', patreonName: null, e621Name: null },
  {
    id: 391,
    name: 'Wanderlustguild',
    patreonName: 'WanderlustGuild',
    e621Name: '007delta',
  },
  { id: 392, name: 'Voregence', patreonName: 'Voregence', e621Name: null },
  { id: 393, name: 'NowandLater', patreonName: 'doubledogcomics', e621Name: null },
  { id: 395, name: 'Catsudon', patreonName: 'catsudon', e621Name: null },
  { id: 396, name: 'PeskyBatfish', patreonName: null, e621Name: 'peskybatfish' },
  { id: 397, name: 'Shikokubo', patreonName: 'Shikokubo', e621Name: null },
  { id: 398, name: 'DeerRobin', patreonName: null, e621Name: null },
  { id: 400, name: 'Dangpa', patreonName: 'dangpa', e621Name: 'dangpa' },
  { id: 401, name: 'Risenpaw', patreonName: 'risenpawarts', e621Name: 'risenpaw' },
  { id: 402, name: 'Cenegan024', patreonName: 'Cenegan', e621Name: 'cenegan024' },
  { id: 403, name: 'Ryoku', patreonName: null, e621Name: 'ryoku' },
  { id: 404, name: 'Phrannd', patreonName: 'Phrannd', e621Name: null },
  {
    id: 405,
    name: 'Thy Carker',
    patreonName: 'https://www.patreon.com/Thy',
    e621Name: null,
  },
  {
    id: 406,
    name: 'Alps Sarsis',
    patreonName: 'https://www.patreon.com/sarsis',
    e621Name: null,
  },
  { id: 407, name: 'DBruin', patreonName: null, e621Name: 'dbruin' },
  { id: 408, name: 'Glass Jaw Boxer', patreonName: null, e621Name: null },
  { id: 409, name: 'Phenya', patreonName: 'phenyaarts', e621Name: 'phenyanyanya' },
  { id: 410, name: 'Drmax', patreonName: 'maxsatan', e621Name: 'drmax' },
  { id: 411, name: 'Nopetrol', patreonName: null, e621Name: null },
  { id: 412, name: 'Elijahelegia', patreonName: null, e621Name: null },
  { id: 413, name: '9Tales Comics', patreonName: '9tales', e621Name: null },
  { id: 414, name: 'JenTheMouse', patreonName: 'jenthemouse', e621Name: null },
  { id: 415, name: 'WolfPsalm', patreonName: 'WolfPsalm', e621Name: 'WolfPsalm' },
  { id: 416, name: 'Gewitter', patreonName: null, e621Name: 'gewitter' },
  { id: 417, name: 'Frenky HW', patreonName: 'frenkyhw', e621Name: 'frenky_hw' },
  { id: 418, name: 'FluffyTuft', patreonName: null, e621Name: 'fluffytuft' },
  { id: 419, name: 'Ziggie13', patreonName: null, e621Name: 'ziggie13' },
  { id: 420, name: 'LaudanumSerum', patreonName: 'ChatNoir', e621Name: 'laudanumserum' },
  { id: 421, name: 'Amadose', patreonName: 'amadose', e621Name: 'amadose' },
  { id: 422, name: 'Omyurice', patreonName: 'omyurice', e621Name: 'omyurice' },
  { id: 423, name: 'Pokilewd', patreonName: 'pokilewd', e621Name: 'pokilewd' },
  { id: 424, name: 'Mcfan', patreonName: 'McFan', e621Name: null },
  {
    id: 425,
    name: 'Youwannaslap',
    patreonName: 'youwannaslap',
    e621Name: 'youwannaslap',
  },
  { id: 426, name: 'JayAxer', patreonName: null, e621Name: null },
  { id: 427, name: 'Nikkibunn', patreonName: 'Nikkibunn', e621Name: 'nikkibunn' },
  { id: 428, name: 'Hacony', patreonName: 'hacony', e621Name: 'hacony' },
  { id: 429, name: 'Nurinaki', patreonName: 'nurinaki', e621Name: 'Nurinaki' },
  { id: 430, name: 'PawSmasher', patreonName: null, e621Name: null },
  { id: 431, name: 'Sunitai', patreonName: null, e621Name: null },
  { id: 432, name: 'Triuni', patreonName: null, e621Name: null },
  { id: 433, name: 'Nickii', patreonName: 'Aoizuri', e621Name: null },
  {
    id: 434,
    name: 'ScruffyTheDeer',
    patreonName: 'https://www.patreon.com/scruffythedeer',
    e621Name: null,
  },
  { id: 435, name: 'Hammytoy', patreonName: 'hammytoy', e621Name: 'Hammytoy' },
  { id: 436, name: 'Silver Edge', patreonName: null, e621Name: null },
  { id: 437, name: 'Arch3y', patreonName: 'Arch3y', e621Name: null },
  { id: 438, name: 'Zourik', patreonName: 'zourik_', e621Name: 'zourik' },
  { id: 439, name: 'Ross', patreonName: null, e621Name: null },
  { id: 440, name: 'Hoshi', patreonName: null, e621Name: null },
  { id: 441, name: 'InsomniacOvrlrd', patreonName: 'InsomniacOvrLrd', e621Name: null },
  { id: 442, name: 'Beez', patreonName: 'Beez_Tiger', e621Name: 'beez' },
  { id: 443, name: 'Zunu-Raptor', patreonName: null, e621Name: null },
  { id: 444, name: 'Fuze', patreonName: 'FuzeDudeArt', e621Name: 'Fuze' },
  { id: 445, name: 'NotAFurfag', patreonName: null, e621Name: null },
  {
    id: 446,
    name: 'Yuguni',
    patreonName: 'https://www.patreon.com/yuguni',
    e621Name: 'https://e621.net/posts?tags=yuguni',
  },
  { id: 447, name: 'FallenInTheDark', patreonName: 'FallenInTheDark', e621Name: null },
  { id: 448, name: 'Nanoff', patreonName: 'Nanoff', e621Name: 'nanoff' },
  { id: 449, name: 'Pukaa', patreonName: 'Pukka', e621Name: null },
  {
    id: 450,
    name: 'Jay-R',
    patreonName: 'https://www.patreon.com/JrGonzales',
    e621Name: null,
  },
  { id: 451, name: 'Lirian', patreonName: 'LirKov', e621Name: null },
  { id: 452, name: 'Theo Young', patreonName: 'theoyoungart', e621Name: 'theo_young' },
  { id: 454, name: 'AmazingGwen', patreonName: 'amazinggwen', e621Name: 'amazinggwen' },
  { id: 455, name: 'MODCA', patreonName: 'modca', e621Name: 'modca' },
  {
    id: 456,
    name: 'Raccon Douglas',
    patreonName: 'RaccDouglas',
    e621Name: 'raccoon_douglas_(artist)',
  },
  { id: 457, name: 'Kumak', patreonName: 'kumakcom', e621Name: 'kumak71395' },
  { id: 458, name: 'Kicktyan', patreonName: null, e621Name: 'kicktyan' },
  { id: 460, name: 'Kivwolf', patreonName: null, e621Name: 'kivwolf' },
  { id: 461, name: 'Ark Warrior', patreonName: null, e621Name: 'ark_warrior' },
  { id: 462, name: 'Manene', patreonName: 'Pantimimi', e621Name: 'manene' },
  { id: 463, name: 'Twiren', patreonName: 'twiren', e621Name: 'twiren' },
  { id: 464, name: 'Kalahari', patreonName: 'kalahari', e621Name: 'kalahari' },
  { id: 466, name: 'Zippy Sqrl', patreonName: null, e621Name: null },
  { id: 467, name: 'ImpXimon', patreonName: null, e621Name: null },
  { id: 468, name: 'Twang', patreonName: null, e621Name: 'twang' },
  { id: 469, name: 'DragonsPonies', patreonName: null, e621Name: 'dragonsponies ' },
  { id: 470, name: 'KomDog', patreonName: ' komdog', e621Name: ' komdog' },
  { id: 471, name: 'Torquewintress', patreonName: 'Goatene', e621Name: 'torquewintress' },
  { id: 473, name: 'Vju79', patreonName: 'vju79', e621Name: 'vju79' },
  {
    id: 474,
    name: 'BluePanda115',
    patreonName: 'bluepanda115',
    e621Name: 'bluepanda115',
  },
  {
    id: 475,
    name: 'Dr.Bubblebum',
    patreonName: 'user?u=35289148',
    e621Name: 'dr.bubblebum',
  },
  { id: 477, name: 'unpopularwolf', patreonName: null, e621Name: null },
  { id: 481, name: 'Haychel', patreonName: 'haychel ', e621Name: 'haychel' },
  { id: 482, name: 'Basch', patreonName: 'BaschWasTaken', e621Name: 'basch' },
  { id: 483, name: 'Argon Vile', patreonName: '', e621Name: 'argon_vile' },
  { id: 484, name: 'Tentabat', patreonName: 'tentabat', e621Name: 'tentabat' },
  { id: 485, name: 'Doost', patreonName: '', e621Name: 'doost' },
  { id: 486, name: 'Dankflank', patreonName: '', e621Name: 'dankflank' },
  { id: 487, name: 'Kwik', patreonName: 'GKCollabs', e621Name: 'kwik_(artist)' },
  { id: 488, name: 'Colonel Klink', patreonName: '', e621Name: 'Colonel_Klink' },
  { id: 489, name: 'Nongqiling', patreonName: '', e621Name: 'nongqiling' },
  { id: 490, name: 'Kyma', patreonName: '', e621Name: 'kyma' },
  { id: 491, name: 'Bleats', patreonName: 'Bleats', e621Name: 'bleats' },
  { id: 492, name: 'Gab Shiba', patreonName: 'gabshiba', e621Name: 'gabshiba' },
  { id: 493, name: 'Pak009', patreonName: 'pak009', e621Name: 'pak009' },
  { id: 494, name: 'Raaz', patreonName: 'RaazCat', e621Name: 'raaz' },
  { id: 495, name: 'Chikiota', patreonName: 'chikiota', e621Name: 'chikiota' },
  { id: 496, name: 'Rastaban', patreonName: '', e621Name: 'rastaban_coal' },
  { id: 497, name: 'Akitokit', patreonName: '', e621Name: 'akitokit' },
  { id: 498, name: 'Lacrimale', patreonName: null, e621Name: null },
  { id: 499, name: 'INAX', patreonName: null, e621Name: null },
  { id: 500, name: 'Kisera', patreonName: 'Kisera', e621Name: null },
  { id: 501, name: 'Berrypunchz', patreonName: '', e621Name: 'strawberrypunchz' },
  { id: 502, name: 'Huka', patreonName: 'Huka', e621Name: 'huka' },
  { id: 503, name: 'Flash_Draw', patreonName: '', e621Name: 'flash_draw' },
  {
    id: 504,
    name: 'EbonyChimera',
    patreonName: 'ebonychimera',
    e621Name: 'ebonychimera',
  },
  { id: 505, name: 'Azurei', patreonName: null, e621Name: 'azurei' },
  { id: 506, name: 'Kaittycat', patreonName: 'Kaittycat', e621Name: null },
  { id: 507, name: 'PB-Baby', patreonName: null, e621Name: 'pb-art' },
  { id: 508, name: 'JackOfak', patreonName: null, e621Name: 'jackofak' },
  { id: 509, name: 'ASTROgraph', patreonName: '', e621Name: 'astrograph' },
  { id: 510, name: 'Baileyx', patreonName: '', e621Name: 'baileyx' },
  { id: 511, name: 'VogelRove', patreonName: null, e621Name: null },
  {
    id: 512,
    name: 'SoftestPuffss',
    patreonName: 'https://www.patreon.com/PuffsAdventures',
    e621Name: null,
  },
  { id: 513, name: 'Zaush', patreonName: null, e621Name: null },
  {
    id: 514,
    name: 'SkellyDoll',
    patreonName: null,
    e621Name: 'skeletonguys-and-ragdolls',
  },
  { id: 515, name: 'Shinodage', patreonName: null, e621Name: 'Shinodage' },
  { id: 516, name: 'Qrichy', patreonName: '', e621Name: 'qrichy' },
  {
    id: 517,
    name: 'ManFromEarth',
    patreonName: 'manfromearth',
    e621Name: 'manfromearth',
  },
  { id: 518, name: 'Perpleon', patreonName: '', e621Name: 'perpleon' },
  { id: 519, name: 'Senz', patreonName: 'FireEagle2015', e621Name: 'senz' },
  { id: 520, name: 'Jizoku', patreonName: ' Jizoku', e621Name: ' jizoku' },
  {
    id: 521,
    name: 'Munkeesgomu',
    patreonName: 'Munkeesgomu',
    e621Name: 'Munks (artist)',
  },
  { id: 522, name: 'Benj24', patreonName: 'benj24', e621Name: 'benj24' },
  { id: 523, name: 'HungotheNomster', patreonName: null, e621Name: 'HungotheNomster' },
  { id: 524, name: 'Thathornycat', patreonName: null, e621Name: 'thathornycat' },
  { id: 525, name: 'Viola bat', patreonName: 'violabat', e621Name: 'viola_bat' },
  { id: 526, name: 'FlickLock', patreonName: null, e621Name: null },
  { id: 527, name: 'Haaru', patreonName: '', e621Name: 'haaru' },
  { id: 528, name: 'Carpetwurm', patreonName: 'carpetwurm', e621Name: 'carpetwurm' },
  { id: 529, name: 'Ultilix', patreonName: null, e621Name: 'ultilix' },
  { id: 530, name: 'InfinityDoom', patreonName: null, e621Name: 'infinitydoom' },
  { id: 531, name: 'Felinesyndr0me', patreonName: null, e621Name: 'felinesyndr0me' },
  {
    id: 532,
    name: 'Kumammoto',
    patreonName: 'kumammoto',
    e621Name: 'kumammoto_(artist)',
  },
  {
    id: 533,
    name: 'Dream And Nightmare',
    patreonName: null,
    e621Name: 'dream_and_nightmare',
  },
  {
    id: 534,
    name: 'Bonnie bovine',
    patreonName: 'bonniebovine',
    e621Name: 'bonnie bovine',
  },
  { id: 535, name: 'Darknessminotaur', patreonName: null, e621Name: 'darknessminotaur' },
  { id: 536, name: 'Zackary911', patreonName: 'zackary911', e621Name: 'Zackary911' },
  { id: 537, name: 'Literaturabdsm', patreonName: null, e621Name: 'literaturabdsm' },
  {
    id: 538,
    name: 'Rainbowscreen',
    patreonName: 'rainbowscreenart',
    e621Name: 'rainbowscreen',
  },
  { id: 539, name: 'Takataka', patreonName: 'takatakapig', e621Name: 'takataka' },
  { id: 540, name: 'Thekinkybear', patreonName: 'TheKBear ', e621Name: 'thekinkybear' },
  { id: 541, name: 'Neko3240', patreonName: null, e621Name: 'neko3240' },
  {
    id: 542,
    name: 'Varknakfrery',
    patreonName: 'varknakfrery',
    e621Name: 'varknakfrery',
  },
  { id: 543, name: 'Paper-Wings', patreonName: 'tailshigh', e621Name: 'paper-wings' },
  { id: 544, name: 'Kihu', patreonName: 'kihu', e621Name: 'kihu' },
  { id: 545, name: 'Seibear', patreonName: null, e621Name: 'seibear' },
  { id: 546, name: 'Conrie', patreonName: null, e621Name: 'conrie' },
  { id: 547, name: 'Mosin', patreonName: 'mosinott', e621Name: 'mosin' },
  { id: 548, name: 'BabyStar', patreonName: 'squiggle', e621Name: 'BabyStart' },
  { id: 549, name: 'Mc C', patreonName: null, e621Name: 'mcc' },
  { id: 550, name: 'Vialu', patreonName: null, e621Name: null },
  { id: 551, name: 'Heresy', patreonName: 'heresyart', e621Name: 'heresy_(artist)' },
  { id: 552, name: 'Team Penny', patreonName: 'nakedpenny', e621Name: 'team_penny' },
  { id: 553, name: 'Milkytiger1145', patreonName: null, e621Name: 'milkytiger1145' },
  { id: 554, name: ' TokifujiWrongOne', patreonName: null, e621Name: null },
  { id: 555, name: 'Elicitie', patreonName: 'Elicitie', e621Name: null },
  { id: 556, name: 'Dalwart', patreonName: 'dalwart', e621Name: 'dalwart' },
  { id: 557, name: 'KantaChibli', patreonName: 'KantaChibli', e621Name: 'KantaChibli' },
  { id: 558, name: 'NaughtyMorg', patreonName: 'naughtymorg', e621Name: 'naughtymorg' },
  { id: 559, name: 'Krazyelf', patreonName: 'KrazyELF', e621Name: null },
  { id: 560, name: 'Iwbitu', patreonName: 'iwbitu', e621Name: 'iwbitu' },
  { id: 561, name: 'DrawPanther', patreonName: 'HardBlush', e621Name: null },
  { id: 562, name: 'Roly', patreonName: null, e621Name: 'roly' },
  {
    id: 563,
    name: 'LapinousMalice',
    patreonName: 'lapinousmalice',
    e621Name: 'lapinousmalice',
  },
  { id: 564, name: 'Armorine', patreonName: 'armorine', e621Name: 'armorine' },
  { id: 565, name: 'Sidnithefox', patreonName: 'SiDniTheFox', e621Name: 'sidnithefox' },
  { id: 566, name: 'Pig', patreonName: 'pigdragonproductions', e621Name: 'pig_(artist)' },
  { id: 567, name: 'Twistedhound', patreonName: null, e621Name: 'twistedhound ' },
  { id: 568, name: 'Echto', patreonName: null, e621Name: 'echto' },
  { id: 569, name: 'VonBoche', patreonName: 'user?u=492668', e621Name: 'Vonboche' },
  { id: 570, name: 'Gumi', patreonName: null, e621Name: 'gumiboie' },
  { id: 571, name: 'Lost-paw', patreonName: 'lostpaw', e621Name: 'lost-paw' },
  { id: 572, name: 'Corrsk', patreonName: 'Corrsk', e621Name: 'corrsk' },
  { id: 574, name: 'VentKazemaru', patreonName: 'stardragon', e621Name: 'ventkazemaru' },
  { id: 575, name: 'Mrpeculiart', patreonName: 'mrpeculiart', e621Name: 'peculiart' },
  { id: 576, name: 'Moon Pearl', patreonName: 'Succubi Samus', e621Name: 'moon_pearl' },
  { id: 577, name: 'Eliana-Asato', patreonName: 'eliana', e621Name: 'eliana-asato' },
  { id: 578, name: 'Nuzzo', patreonName: null, e621Name: 'nuzzo' },
  { id: 579, name: 'Husky92', patreonName: 'husky92', e621Name: 'husky92' },
  { id: 580, name: 'ZoulEtSentiment', patreonName: null, e621Name: 'zouletsentiment' },
  { id: 581, name: 'AbZ Comics', patreonName: 'AbZComics', e621Name: null },
  { id: 582, name: 'UtopianVee', patreonName: null, e621Name: 'utopianvee' },
  { id: 583, name: 'Dullehan', patreonName: null, e621Name: 'dullehan' },
  { id: 584, name: 'Bastriw', patreonName: 'Bastriw', e621Name: 'bastriw' },
  { id: 585, name: 'HolidayPup', patreonName: null, e621Name: 'holidaypup' },
  { id: 586, name: 'Ruby-Milk', patreonName: null, e621Name: null },
  {
    id: 590,
    name: 'PawpadComrade',
    patreonName: 'PawpadComrade',
    e621Name: 'pawpadcomrade',
  },
  { id: 591, name: 'Rick Griffin', patreonName: 'rickgriffin', e621Name: 'rick_griffin' },
  {
    id: 592,
    name: 'JedaySkayVoker',
    patreonName: 'jedayskayvoker',
    e621Name: 'jedayskayvoker',
  },
  { id: 593, name: 'BadWagon', patreonName: 'badwagon', e621Name: 'chonkywagon' },
  { id: 594, name: 'DragonFU', patreonName: 'DragonFU', e621Name: 'dragonfu' },
  { id: 595, name: 'Yelocrom', patreonName: null, e621Name: null },
  { id: 596, name: 'SXFPantera', patreonName: 'PantheraDraws', e621Name: 'sxfpantera' },
  { id: 597, name: 'Kyokimute', patreonName: null, e621Name: 'rhk' },
  { id: 598, name: 'Quillu', patreonName: null, e621Name: 'quillu' },
  { id: 599, name: 'Kittenmod', patreonName: null, e621Name: 'kittenmod' },
  { id: 600, name: 'Nowykowski', patreonName: null, e621Name: 'nowykowski7' },
  {
    id: 601,
    name: 'Jcosneverexisted',
    patreonName: 'jcosneverexisted',
    e621Name: 'jcosneverexisted',
  },
  { id: 602, name: 'Dweet-Tea', patreonName: null, e621Name: 'dweet-tea' },
  { id: 603, name: 'Fetimation', patreonName: 'fetimation', e621Name: 'fetimation ' },
  { id: 604, name: 'Sframboob ', patreonName: null, e621Name: 'sframboob ' },
  { id: 605, name: 'K0suna', patreonName: null, e621Name: 'k0suna' },
  { id: 606, name: 'IPoke', patreonName: null, e621Name: 'ipoke' },
  { id: 607, name: 'Jishinu', patreonName: 'JishinuArt', e621Name: 'jishinu ' },
  { id: 608, name: 'Subject', patreonName: 'Subject', e621Name: 'subject_(artist)' },
  { id: 610, name: 'StePandy', patreonName: 'StePanda', e621Name: 'stepanda' },
  { id: 611, name: 'WhateverBender', patreonName: null, e621Name: null },
  { id: 612, name: 'K-9', patreonName: 'ArtMutt', e621Name: 'k-9' },
  {
    id: 613,
    name: 'MongoArt',
    patreonName: 'https://www.patreon.com/MongoArt',
    e621Name: '3mangos',
  },
  { id: 614, name: 'Travon', patreonName: null, e621Name: null },
  { id: 615, name: 'Maneating Kangaroo', patreonName: null, e621Name: null },
  {
    id: 616,
    name: 'Balmos',
    patreonName: 'https://www.patreon.com/balmos',
    e621Name: null,
  },
  { id: 617, name: 'Spirit Dancer', patreonName: null, e621Name: null },
  { id: 619, name: 'ReDoXX', patreonName: null, e621Name: 'redoxx ' },
  { id: 621, name: 'Zhadart', patreonName: null, e621Name: 'zhadart' },
  { id: 623, name: 'Ofuro', patreonName: null, e621Name: 'ofuro' },
  { id: 624, name: 'Confusedraven', patreonName: null, e621Name: 'confusedraven' },
  {
    id: 625,
    name: 'Keetch',
    patreonName: 'https://www.patreon.com/keeetch',
    e621Name: null,
  },
  { id: 626, name: 'JakeTheHare', patreonName: '', e621Name: 'jakethegoat' },
  { id: 627, name: 'Mancoin', patreonName: null, e621Name: null },
  { id: 628, name: 'Oro', patreonName: 'Oro97', e621Name: null },
  { id: 629, name: 'Falcrus', patreonName: 'Falcrus', e621Name: 'falcrus' },
  { id: 630, name: 'JooJoo', patreonName: null, e621Name: 'stickybreadbarbarian' },
  { id: 631, name: 'NX-3000', patreonName: 'nx3000', e621Name: 'nx-3000' },
  { id: 632, name: 'Roseonapot', patreonName: 'BurnntToast', e621Name: null },
  { id: 633, name: 'Oxfort2199', patreonName: null, e621Name: 'oxfort2199' },
  { id: 634, name: 'Jinxit', patreonName: 'dont_jinxit', e621Name: 'jinxit' },
  { id: 635, name: 'CyanCapsule', patreonName: 'CyanCapsule', e621Name: null },
  { id: 636, name: 'Evomanaphy', patreonName: 'evomanaphy', e621Name: null },
];
