export default [
  { name: 'abdl', id: 862, count: 4 },
  { name: 'absol', id: 1, count: 7 },
  { name: 'abuse', id: 882, count: 1 },
  { name: 'age difference', id: 2, count: 56 },
  { name: 'aggressive retsuko', id: 326, count: 2 },
  { name: 'alligator', id: 3, count: 19 },
  { name: 'alpaca', id: 4, count: 1 },
  { name: 'ampharos', id: 827, count: 1 },
  { name: 'anal', id: 5, count: 800 },
  { name: 'andromorph', id: 875, count: 5 },
  { name: 'animal crossing', id: 6, count: 3 },
  { name: 'animatronic', id: 838, count: 1 },
  { name: 'anon-kun', id: 7, count: 3 },
  { name: 'anthro', id: 8, count: 1143 },
  { name: 'anubis', id: 9, count: 5 },
  { name: 'apple bloom', id: 10, count: 4 },
  { name: 'applejack', id: 11, count: 12 },
  { name: 'arcanine', id: 12, count: 11 },
  { name: 'asgore', id: 13, count: 2 },
  { name: 'asriel', id: 14, count: 4 },
  { name: 'autofellatio', id: 15, count: 5 },
  { name: 'avian', id: 16, count: 64 },
  { name: 'badger', id: 17, count: 2 },
  { name: 'bambi', id: 18, count: 2 },
  { name: 'banjo kazooie', id: 830, count: 1 },
  { name: 'bara', id: 853, count: 4 },
  { name: 'bat', id: 19, count: 25 },
  { name: 'bdsm', id: 20, count: 97 },
  { name: 'bear', id: 21, count: 40 },
  { name: 'beastars', id: 320, count: 7 },
  { name: 'belly bulge', id: 22, count: 43 },
  { name: 'big ass', id: 23, count: 100 },
  { name: 'big balls', id: 24, count: 57 },
  { name: 'big boobs', id: 25, count: 163 },
  { name: 'big mac', id: 26, count: 5 },
  { name: 'big penis', id: 27, count: 291 },
  { name: 'bird', id: 28, count: 34 },
  { name: 'biting', id: 29, count: 27 },
  { name: 'blaziken', id: 30, count: 5 },
  { name: 'blindfolded', id: 836, count: 7 },
  { name: 'blood', id: 31, count: 42 },
  { name: 'blowjob', id: 32, count: 784 },
  { name: 'bondage', id: 308, count: 35 },
  { name: 'bovine', id: 33, count: 45 },
  { name: 'bowser', id: 34, count: 2 },
  { name: 'braeburn', id: 35, count: 1 },
  { name: 'braixen', id: 36, count: 7 },
  { name: 'breloom', id: 37, count: 1 },
  { name: 'brother and sister', id: 876, count: 1 },
  { name: 'buizel', id: 38, count: 3 },
  { name: 'bukkake', id: 39, count: 16 },
  { name: 'bulbasaur', id: 40, count: 2 },
  { name: 'bull', id: 867, count: 4 },
  { name: 'bunny', id: 41, count: 103 },
  { name: 'buttplug', id: 873, count: 6 },
  { name: 'canine', id: 42, count: 571 },
  { name: 'canine penis', id: 43, count: 164 },
  { name: 'casual nudity', id: 808, count: 10 },
  { name: 'cat', id: 44, count: 106 },
  { name: 'caught', id: 45, count: 97 },
  { name: 'charizard', id: 46, count: 20 },
  { name: 'charmander', id: 311, count: 3 },
  { name: 'charmeleon', id: 47, count: 6 },
  { name: 'chastity', id: 48, count: 15 },
  { name: 'cheetah', id: 49, count: 34 },
  { name: 'chespin', id: 50, count: 2 },
  { name: 'chief bogo', id: 51, count: 1 },
  { name: 'chikorita', id: 863, count: 1 },
  { name: 'chipmunk', id: 52, count: 3 },
  { name: 'choking', id: 822, count: 1 },
  { name: 'christmas', id: 53, count: 18 },
  { name: 'chubby', id: 865, count: 6 },
  { name: 'cinderace', id: 329, count: 1 },
  { name: 'cock vore', id: 847, count: 3 },
  { name: 'combusken', id: 54, count: 1 },
  { name: 'condom', id: 831, count: 9 },
  { name: 'corruption', id: 885, count: 1 },
  { name: 'cow', id: 55, count: 15 },
  { name: 'creampie', id: 56, count: 292 },
  { name: 'creampie eating', id: 872, count: 5 },
  { name: 'crocodile', id: 874, count: 1 },
  { name: 'crossdressing', id: 57, count: 43 },
  { name: 'cubone', id: 817, count: 1 },
  { name: 'cucksibold', id: 59, count: 3 },
  { name: 'cum in ass', id: 800, count: 110 },
  { name: 'cum in mouth', id: 60, count: 235 },
  { name: 'cum inside', id: 799, count: 134 },
  { name: 'cum on face', id: 803, count: 36 },
  { name: 'cumflation', id: 61, count: 37 },
  { name: 'cumshot', id: 62, count: 376 },
  { name: 'cunnilingus', id: 63, count: 233 },
  { name: 'curvy', id: 64, count: 75 },
  { name: 'cute', id: 65, count: 112 },
  { name: 'dad x son', id: 899, count: 1 },
  { name: 'deepthroat', id: 856, count: 19 },
  { name: 'deer', id: 66, count: 76 },
  { name: 'deino', id: 67, count: 1 },
  { name: 'demon', id: 68, count: 16 },
  { name: 'derpy', id: 69, count: 2 },
  { name: 'dewott', id: 826, count: 2 },
  { name: 'diaper', id: 70, count: 7 },
  { name: 'dick on dick', id: 71, count: 29 },
  { name: 'digestion', id: 805, count: 2 },
  { name: 'digimon', id: 72, count: 9 },
  { name: 'dinosaur', id: 73, count: 8 },
  { name: 'discord', id: 74, count: 3 },
  { name: 'dog', id: 75, count: 188 },
  { name: 'donkey', id: 76, count: 15 },
  { name: 'double penetration', id: 77, count: 101 },
  { name: 'double penis', id: 818, count: 8 },
  { name: 'draenei', id: 78, count: 7 },
  { name: 'dragon', id: 79, count: 163 },
  { name: 'duck', id: 80, count: 2 },
  { name: 'dust', id: 81, count: 1 },
  { name: 'e-stim', id: 866, count: 1 },
  { name: 'eevee', id: 82, count: 16 },
  { name: 'eggs', id: 83, count: 14 },
  { name: 'elephant', id: 84, count: 6 },
  { name: 'elf', id: 85, count: 5 },
  { name: 'emolga', id: 86, count: 1 },
  { name: 'emotional', id: 87, count: 14 },
  { name: 'equine', id: 88, count: 184 },
  { name: 'espeon', id: 89, count: 7 },
  { name: 'excessive cum', id: 802, count: 44 },
  { name: 'exhibitionism', id: 901, count: 4 },
  { name: 'facesitting', id: 90, count: 47 },
  { name: 'falco lombardi', id: 91, count: 2 },
  { name: 'fanmadeby:tricksta', id: 918, count: 1 },
  { name: 'fat', id: 92, count: 26 },
  { name: 'father and daugher', id: 878, count: 1 },
  { name: 'father and son', id: 879, count: 4 },
  { name: 'feet', id: 93, count: 42 },
  { name: 'feline', id: 94, count: 316 },
  { name: 'femboy', id: 95, count: 140 },
  { name: 'femdom', id: 96, count: 34 },
  { name: 'fennec', id: 97, count: 15 },
  { name: 'fennekin', id: 98, count: 2 },
  { name: 'feral', id: 99, count: 187 },
  { name: 'feral penis', id: 100, count: 227 },
  { name: 'feral vagina', id: 101, count: 34 },
  { name: 'feraligatr', id: 102, count: 4 },
  { name: 'fetish', id: 894, count: 2 },
  { name: 'fidget', id: 103, count: 1 },
  { name: 'fingering', id: 104, count: 181 },
  { name: 'finnick', id: 105, count: 2 },
  { name: 'fisting', id: 106, count: 7 },
  { name: 'fizzle', id: 107, count: 2 },
  { name: 'flamedramon', id: 108, count: 2 },
  { name: 'flareon', id: 109, count: 6 },
  { name: 'fluttershy', id: 110, count: 10 },
  { name: 'flygon', id: 111, count: 1 },
  { name: 'fnaf', id: 112, count: 4 },
  { name: 'footjob', id: 113, count: 21 },
  { name: 'foreskin', id: 798, count: 18 },
  { name: 'fox', id: 114, count: 181 },
  { name: 'fox mccloud', id: 115, count: 3 },
  { name: 'frog', id: 317, count: 3 },
  { name: 'frogadier', id: 116, count: 1 },
  { name: 'frotting', id: 117, count: 31 },
  { name: 'gag', id: 861, count: 11 },
  { name: 'gangbang', id: 868, count: 4 },
  { name: 'gaping', id: 837, count: 15 },
  { name: 'garble', id: 118, count: 2 },
  { name: 'garchomp', id: 119, count: 4 },
  { name: 'gardevoir', id: 120, count: 3 },
  { name: 'gatomon', id: 121, count: 1 },
  { name: 'gay', id: 892, count: 20 },
  { name: 'gay sex', id: 891, count: 7 },
  { name: 'gazelle', id: 123, count: 10 },
  { name: 'gilda', id: 124, count: 1 },
  { name: 'giraffe', id: 125, count: 18 },
  { name: 'glaceon', id: 126, count: 12 },
  { name: 'goat', id: 127, count: 32 },
  { name: 'goblin', id: 128, count: 2 },
  { name: 'goo creature', id: 129, count: 5 },
  { name: 'goodra', id: 330, count: 4 },
  { name: 'gore', id: 887, count: 1 },
  { name: 'gouhin', id: 324, count: 2 },
  { name: 'greninja', id: 130, count: 2 },
  { name: 'griffin', id: 131, count: 7 },
  { name: 'group', id: 132, count: 227 },
  { name: 'group sex', id: 893, count: 4 },
  { name: 'grovyle', id: 133, count: 3 },
  { name: 'growlithe', id: 134, count: 2 },
  { name: 'growth', id: 902, count: 1 },
  { name: 'guardians of the galaxy', id: 813, count: 1 },
  { name: 'gym', id: 840, count: 3 },
  { name: 'haida', id: 327, count: 2 },
  { name: 'handjob', id: 135, count: 149 },
  { name: 'hands free', id: 857, count: 6 },
  { name: 'hard vore', id: 136, count: 4 },
  { name: 'harness', id: 835, count: 1 },
  { name: 'herm', id: 305, count: 8 },
  { name: 'hero to villain conversion', id: 888, count: 1 },
  { name: 'horse', id: 137, count: 119 },
  { name: 'horsecock', id: 138, count: 142 },
  { name: 'houndoom', id: 139, count: 3 },
  { name: 'houndor', id: 824, count: 1 },
  { name: 'human', id: 140, count: 97 },
  { name: 'humiliation', id: 141, count: 27 },
  { name: 'husky', id: 881, count: 3 },
  { name: 'hydreigon', id: 142, count: 1 },
  { name: 'hyena', id: 143, count: 18 },
  { name: 'hyper', id: 144, count: 16 },
  { name: 'hypnosis', id: 145, count: 36 },
  { name: 'impmon', id: 146, count: 2 },
  { name: 'impregnation', id: 806, count: 45 },
  { name: 'in heat', id: 147, count: 26 },
  { name: 'in public', id: 148, count: 147 },
  { name: 'incest', id: 149, count: 105 },
  { name: 'incineroar', id: 313, count: 4 },
  { name: 'inflation', id: 150, count: 17 },
  { name: 'isabelle', id: 151, count: 2 },
  { name: 'jack', id: 323, count: 3 },
  { name: 'jackal', id: 152, count: 10 },
  { name: 'jolteon', id: 153, count: 6 },
  { name: 'judy hopps', id: 154, count: 26 },
  { name: 'kalista', id: 155, count: 1 },
  { name: 'kangaroo', id: 156, count: 10 },
  { name: 'kindred', id: 157, count: 2 },
  { name: 'king sombra', id: 158, count: 5 },
  { name: 'kissing', id: 159, count: 327 },
  { name: 'knotting', id: 160, count: 136 },
  { name: 'knuckles', id: 161, count: 1 },
  { name: 'kommo-o', id: 162, count: 1 },
  { name: 'krystal', id: 163, count: 3 },
  { name: 'kung fu panda', id: 890, count: 1 },
  { name: 'lapras', id: 332, count: 1 },
  { name: 'latex', id: 829, count: 8 },
  { name: 'leafeon', id: 164, count: 5 },
  { name: 'league of legends', id: 165, count: 4 },
  { name: 'leavanny', id: 166, count: 1 },
  { name: 'legoshi', id: 321, count: 6 },
  { name: 'lemur', id: 167, count: 1 },
  { name: 'leopard', id: 168, count: 11 },
  { name: 'licking', id: 169, count: 129 },
  { name: 'lion', id: 170, count: 51 },
  { name: 'litten', id: 318, count: 2 },
  { name: 'lizard', id: 171, count: 29 },
  { name: 'locker room', id: 839, count: 6 },
  { name: 'long story', id: 172, count: 149 },
  { name: 'loona', id: 833, count: 2 },
  { name: 'lopunny', id: 173, count: 2 },
  { name: 'louis', id: 325, count: 2 },
  { name: 'lucario', id: 174, count: 24 },
  { name: 'lugia', id: 175, count: 10 },
  { name: 'luxray', id: 176, count: 9 },
  { name: 'lycanroc', id: 177, count: 8 },
  { name: 'lynx', id: 178, count: 28 },
  { name: 'macro', id: 871, count: 2 },
  { name: 'magic', id: 179, count: 40 },
  { name: 'maid', id: 312, count: 6 },
  { name: 'masturbation', id: 180, count: 190 },
  { name: 'meowth', id: 815, count: 1 },
  { name: 'mewtwo', id: 319, count: 2 },
  { name: 'milk', id: 309, count: 3 },
  { name: 'minccino', id: 819, count: 3 },
  { name: 'mind control', id: 883, count: 1 },
  { name: 'minun', id: 820, count: 2 },
  { name: 'misdreavus', id: 181, count: 1 },
  { name: 'monkey', id: 182, count: 6 },
  { name: 'monster', id: 183, count: 40 },
  { name: 'mordecai (regular show)', id: 810, count: 2 },
  { name: 'mother and daughter', id: 880, count: 1 },
  { name: 'mother and son', id: 807, count: 7 },
  { name: 'mouse', id: 184, count: 36 },
  { name: 'muscular', id: 185, count: 111 },
  { name: 'nasus', id: 186, count: 1 },
  { name: 'nick wilde', id: 187, count: 25 },
  { name: 'night elf', id: 188, count: 2 },
  { name: 'ninetales', id: 189, count: 3 },
  { name: 'non-anthro', id: 834, count: 4 },
  { name: 'okapi', id: 190, count: 1 },
  { name: 'on top', id: 916, count: 1 },
  { name: 'oral', id: 315, count: 158 },
  { name: 'orc', id: 191, count: 1 },
  { name: 'orca', id: 192, count: 9 },
  { name: 'orgy', id: 844, count: 4 },
  { name: 'oryx', id: 193, count: 7 },
  { name: 'otter', id: 194, count: 31 },
  { name: 'outside', id: 195, count: 144 },
  { name: 'ox', id: 196, count: 6 },
  { name: 'pachirisu', id: 197, count: 3 },
  { name: 'pancham', id: 825, count: 1 },
  { name: 'panda', id: 198, count: 25 },
  { name: 'pandaren', id: 199, count: 1 },
  { name: 'panther', id: 200, count: 20 },
  { name: 'pegging', id: 201, count: 12 },
  { name: 'photography', id: 202, count: 6 },
  { name: 'pichu', id: 821, count: 1 },
  { name: 'pig', id: 203, count: 7 },
  { name: 'pikachu', id: 204, count: 7 },
  { name: 'pinkie pie', id: 205, count: 13 },
  { name: 'polar bear', id: 206, count: 6 },
  { name: 'police', id: 207, count: 4 },
  { name: 'pony', id: 208, count: 83 },
  { name: 'portal panties', id: 809, count: 5 },
  { name: 'power bottom', id: 917, count: 2 },
  { name: 'presenting', id: 333, count: 16 },
  { name: 'princess cadance', id: 209, count: 7 },
  { name: 'princess celestia', id: 210, count: 9 },
  { name: 'princess luna', id: 211, count: 10 },
  { name: 'public indecency', id: 900, count: 1 },
  { name: 'public sex', id: 905, count: 2 },
  { name: 'purugly', id: 814, count: 1 },
  { name: 'queen chrysalis', id: 212, count: 3 },
  { name: 'quilava', id: 310, count: 5 },
  { name: 'rabbit', id: 213, count: 33 },
  { name: 'raccoon', id: 214, count: 19 },
  { name: 'raichu', id: 215, count: 6 },
  { name: 'rainbow dash', id: 216, count: 14 },
  { name: 'rape', id: 217, count: 94 },
  { name: 'rapidash', id: 852, count: 1 },
  { name: 'raptor', id: 218, count: 5 },
  { name: 'rarity', id: 219, count: 8 },
  { name: 'rat', id: 220, count: 18 },
  { name: 'ratchet', id: 221, count: 2 },
  { name: 'rattata', id: 222, count: 4 },
  { name: 'reality warping', id: 884, count: 1 },
  { name: 'red panda', id: 224, count: 9 },
  { name: 'regular show', id: 812, count: 2 },
  { name: 'removing_the_comic_because_of_tos', id: 919, count: 1 },
  { name: 'renamon', id: 225, count: 6 },
  { name: 'renekton', id: 226, count: 1 },
  { name: 'revenge', id: 227, count: 5 },
  { name: 'rhino', id: 228, count: 5 },
  { name: 'riding', id: 915, count: 1 },
  { name: 'rigby (regular show)', id: 811, count: 2 },
  { name: 'rimjob', id: 906, count: 2 },
  { name: 'rimming', id: 229, count: 181 },
  { name: 'riolu', id: 230, count: 4 },
  { name: 'robot', id: 231, count: 6 },
  { name: 'rocket raccoon', id: 232, count: 3 },
  { name: 'rogue the bat', id: 233, count: 1 },
  { name: 'role reversal', id: 845, count: 1 },
  { name: 'romantic', id: 234, count: 70 },
  { name: 'ronno', id: 235, count: 2 },
  { name: 'sabertooth', id: 236, count: 6 },
  { name: 'saliva', id: 237, count: 42 },
  { name: 'sally acorn', id: 238, count: 1 },
  { name: 'sandshrew', id: 239, count: 1 },
  { name: 'scalie', id: 240, count: 177 },
  { name: 'scat', id: 869, count: 1 },
  { name: 'sceptile', id: 241, count: 2 },
  { name: 'scissoring', id: 242, count: 12 },
  { name: 'scizor', id: 243, count: 1 },
  { name: 'scootaloo', id: 244, count: 3 },
  { name: 'scratching', id: 850, count: 2 },
  { name: 'sea lion', id: 245, count: 1 },
  { name: 'sex change', id: 246, count: 36 },
  { name: 'sex slave', id: 889, count: 1 },
  { name: 'sex toy', id: 247, count: 141 },
  { name: 'sexting', id: 848, count: 2 },
  { name: 'shark', id: 248, count: 29 },
  { name: 'sheath play', id: 801, count: 3 },
  { name: 'sheep', id: 249, count: 15 },
  { name: 'shibari', id: 859, count: 3 },
  { name: 'shining armor', id: 250, count: 6 },
  { name: 'shinx', id: 251, count: 3 },
  { name: 'siblings', id: 877, count: 4 },
  { name: 'size difference', id: 252, count: 188 },
  { name: 'skunk', id: 253, count: 11 },
  { name: 'sleeping', id: 331, count: 18 },
  { name: 'slime creature', id: 254, count: 6 },
  { name: 'slit', id: 307, count: 29 },
  { name: 'sly cooper', id: 255, count: 1 },
  { name: 'small boobs', id: 860, count: 6 },
  { name: 'snake', id: 256, count: 29 },
  { name: 'sneasel', id: 257, count: 1 },
  { name: 'sniffing', id: 842, count: 5 },
  { name: 'solo', id: 903, count: 1 },
  { name: 'sonic the hedgehog', id: 258, count: 5 },
  { name: 'soraka', id: 259, count: 1 },
  { name: 'spanking', id: 260, count: 16 },
  { name: 'spike', id: 261, count: 8 },
  { name: 'spitroast', id: 904, count: 1 },
  { name: 'spyro', id: 306, count: 5 },
  { name: 'squirrel', id: 262, count: 18 },
  { name: 'starfox', id: 908, count: 1 },
  { name: 'story', id: 263, count: 258 },
  { name: 'straight to gay conversion', id: 886, count: 1 },
  { name: 'strangulation', id: 823, count: 1 },
  { name: 'streaking', id: 870, count: 1 },
  { name: 'surprise gay', id: 264, count: 55 },
  { name: 'sweaty', id: 265, count: 10 },
  { name: 'sweetie belle', id: 266, count: 3 },
  { name: 'sylveon', id: 267, count: 11 },
  { name: 'tadano', id: 328, count: 1 },
  { name: 'tail play', id: 804, count: 2 },
  { name: 'tailfucking', id: 268, count: 10 },
  { name: 'tauren', id: 269, count: 3 },
  { name: 'tentacles', id: 270, count: 58 },
  { name: 'threesome', id: 832, count: 22 },
  { name: 'tickling', id: 828, count: 4 },
  { name: 'tiger', id: 275, count: 57 },
  { name: 'titjob', id: 276, count: 40 },
  { name: 'toriel', id: 277, count: 2 },
  { name: 'torracat', id: 314, count: 1 },
  { name: 'torture', id: 849, count: 3 },
  { name: 'trans', id: 858, count: 18 },
  { name: 'transformation', id: 278, count: 98 },
  { name: 'treecko', id: 279, count: 1 },
  { name: 'trixie', id: 280, count: 2 },
  { name: 'troll', id: 281, count: 4 },
  { name: 'turtle', id: 282, count: 5 },
  { name: 'twilight sparkle', id: 283, count: 30 },
  { name: 'twink', id: 843, count: 7 },
  { name: 'twokinds', id: 284, count: 1 },
  { name: 'typhlosion', id: 316, count: 4 },
  { name: 'umbreon', id: 285, count: 17 },
  { name: 'undertale', id: 286, count: 8 },
  { name: 'underwear', id: 841, count: 14 },
  { name: 'unicorn', id: 287, count: 15 },
  { name: 'unwilling', id: 288, count: 45 },
  { name: 'vaginal', id: 289, count: 564 },
  { name: 'vaporeon', id: 290, count: 9 },
  { name: 'violence', id: 291, count: 40 },
  { name: 'vore', id: 292, count: 24 },
  { name: 'vulpix', id: 293, count: 8 },
  { name: 'watersports', id: 294, count: 13 },
  { name: 'weavile', id: 295, count: 3 },
  { name: 'werewolf', id: 296, count: 15 },
  { name: 'wolf', id: 297, count: 209 },
  { name: 'worgen', id: 298, count: 2 },
  { name: 'workplace sex', id: 907, count: 3 },
  { name: 'yaoi', id: 864, count: 1 },
  { name: 'yveltal', id: 299, count: 4 },
  { name: 'zebra', id: 300, count: 23 },
  { name: 'zed', id: 301, count: 1 },
  { name: 'zeraora', id: 851, count: 1 },
  { name: 'zootopia', id: 302, count: 32 },
  { name: 'zoroark', id: 303, count: 10 },
  { name: 'zorua', id: 304, count: 2 },
];
