export default [
  {
    artist: 'Ultilix',
    id: 439,
    name: 'Leo: Truth or Dare',
    modName: 'Tunneltundra',
    errorText: 'Malann will fix',
    cat: 'Furry',
    tag: 'MM',
    numberOfPages: 7,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: ['anal', 'dragon', 'frog', 'kissing', 'lizard', 'non-anthro'],
  },
  {
    artist: 'Scappo',
    id: 518,
    name: 'Sleepless Nights',
    modName: 'myzi',
    errorText: null,
    cat: 'Furry',
    tag: 'MF',
    numberOfPages: 31,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: '2022-09-25T00:00:00.000Z',
    keywords: [
      'blowjob',
      'bondage',
      'creampie',
      'cum in mouth',
      'cum inside',
      'gag',
      'goo creature',
      'jackal',
      'licking',
      'size difference',
      'sleeping',
      'snake',
      'threesome',
      'vaginal',
    ],
  },
  {
    artist: 'Maririn',
    id: 542,
    name: 'Brothers in Arms 2',
    modName: 'myzi',
    errorText: 'Page res',
    cat: 'Furry',
    tag: 'MM',
    numberOfPages: 59,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: [
      'anal',
      'anthro',
      'creampie',
      'cum in ass',
      'kissing',
      'long story',
      'panther',
      'tiger',
    ],
  },
  {
    artist: 'Elvche',
    id: 607,
    name: 'Waste Of Time',
    modName: 'Hellpony',
    errorText: null,
    cat: 'Furry',
    tag: 'FF',
    numberOfPages: 59,
    state: 'wip',
    hasThumbnail: 1,
    scheduledPublish: '2022-09-27T00:00:00.000Z',
    keywords: ['fingering', 'scalie', 'size difference', 'story', 'vaginal'],
  },
  {
    artist: 'Keetch',
    id: 675,
    name: 'Chicas',
    modName: 'Inceptions',
    errorText: null,
    cat: 'MLP',
    tag: 'MF',
    numberOfPages: 13,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: '2022-09-29T00:00:00.000Z',
    keywords: [
      'blowjob',
      'creampie',
      'cunnilingus',
      'horsecock',
      'kissing',
      'pony',
      'vaginal',
    ],
  },
  {
    artist: 'Kayla-Na',
    id: 697,
    name: 'Hot Shower',
    modName: 'KeksToGo',
    errorText: 'Low res',
    cat: 'Pokemon',
    tag: 'MF',
    numberOfPages: 31,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: ['anthro', 'cum inside', 'human', 'licking', 'vaginal'],
  },
  {
    artist: 'Jinxit',
    id: 700,
    name: 'Strapped On',
    modName: 'KeksToGo',
    errorText: null,
    cat: 'Furry',
    tag: 'MF',
    numberOfPages: 5,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: '2022-09-24T00:00:00.000Z',
    keywords: [
      'anal',
      'anthro',
      'bdsm',
      'canine',
      'cum on face',
      'cumshot',
      'pegging',
      'red panda',
      'wolf',
    ],
  },
  {
    artist: 'Funkybun',
    id: 701,
    name: 'Too Big To Fit 2',
    modName: 'KeksToGo',
    errorText: null,
    cat: 'Furry',
    tag: 'MF',
    numberOfPages: 16,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: '2022-09-30T00:00:00.000Z',
    keywords: [
      'belly bulge',
      'blowjob',
      'bunny',
      'cum inside',
      'group',
      'horsecock',
      'in public',
    ],
  },
  {
    artist: 'Funkybun',
    id: 702,
    name: 'Casually Naked',
    modName: 'KeksToGo',
    errorText: null,
    cat: 'Furry',
    tag: 'MF',
    numberOfPages: 22,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: '2022-10-01T00:00:00.000Z',
    keywords: [
      'anthro',
      'blowjob',
      'casual nudity',
      'cum in mouth',
      'deepthroat',
      'masturbation',
    ],
  },
  {
    artist: 'Eltonpot',
    id: 719,
    name: 'Feast For 2',
    modName: 'KeksToGo',
    errorText: null,
    cat: 'Furry',
    tag: 'MF',
    numberOfPages: 7,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: '2022-10-03T00:00:00.000Z',
    keywords: [
      'anal',
      'anthro',
      'deepthroat',
      'deer',
      'double penetration',
      'group sex',
      'hyena',
      'threesome',
      'vaginal',
    ],
  },
  {
    artist: 'Zummeng',
    id: 720,
    name: 'Givin Some Inspiration',
    modName: 'KeksToGo',
    errorText: null,
    cat: 'Furry',
    tag: 'MF',
    numberOfPages: 3,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: '2022-10-06T00:00:00.000Z',
    keywords: ['anthro', 'canine', 'cum inside', 'kissing', 'licking', 'vaginal', 'wolf'],
  },
  {
    artist: 'Zummeng',
    id: 721,
    name: 'Sweet Threesome',
    modName: 'KeksToGo',
    errorText: null,
    cat: 'Furry',
    tag: 'MF+',
    numberOfPages: 4,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: '2022-10-08T00:00:00.000Z',
    keywords: [
      'anal',
      'anthro',
      'caught',
      'cum in ass',
      'cum inside',
      'group sex',
      'vaginal',
    ],
  },
  {
    artist: 'SnoopJAY2',
    id: 723,
    name: 'Laundry Day 2',
    modName: 'DasPauluteli',
    errorText: null,
    cat: 'Furry',
    tag: 'MM',
    numberOfPages: 21,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: '2022-10-10T00:00:00.000Z',
    keywords: [
      'age difference',
      'big balls',
      'big penis',
      'caught',
      'cumshot',
      'father and son',
      'horse',
      'horsecock',
      'incest',
      'masturbation',
    ],
  },
  {
    artist: 'Trigaroo',
    id: 724,
    name: 'Salvation',
    modName: 'DasPauluteli',
    errorText: null,
    cat: 'Pokemon',
    tag: 'FF',
    numberOfPages: 27,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: '2022-10-12T00:00:00.000Z',
    keywords: [
      'caught',
      'cum on face',
      'cumshot',
      'cunnilingus',
      'deepthroat',
      'facesitting',
      'feet',
      'femdom',
      'feral',
      'feral penis',
      'feral vagina',
      'licking',
      'masturbation',
      'oral',
      'pegging',
      'saliva',
      'sex slave',
      'sex toy',
      'sleeping',
      'story',
      'vaginal',
    ],
  },
  {
    artist: 'VentKazemaru',
    id: 725,
    name: 'Dog Days',
    modName: 'linxwolf',
    errorText: null,
    cat: 'Furry',
    tag: 'MM',
    numberOfPages: 21,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: '2022-10-15T00:00:00.000Z',
    keywords: [
      'canine',
      'caught',
      'chubby',
      'cumshot',
      'dog',
      'handjob',
      'hands free',
      'kissing',
      'masturbation',
    ],
  },
  {
    artist: 'Tyroo',
    id: 726,
    name: 'Gym Meat-Up',
    modName: 'linxwolf',
    errorText: null,
    cat: 'Furry',
    tag: 'MM',
    numberOfPages: 8,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: '2022-10-17T00:00:00.000Z',
    keywords: [
      'anal',
      'belly bulge',
      'big penis',
      'biting',
      'cum in ass',
      'cum inside',
      'cumflation',
      'excessive cum',
      'femboy',
      'gay',
      'gay sex',
      'gym',
      'inflation',
      'kangaroo',
      'locker room',
      'size difference',
    ],
  },
  {
    artist: 'JedaySkayVoker',
    id: 727,
    name: 'Play the Record - Chapter 3',
    modName: 'atreidae',
    errorText: null,
    cat: 'MLP',
    tag: 'MM',
    numberOfPages: 10,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: [
      'bdsm',
      'bondage',
      'buttplug',
      'chastity',
      'crossdressing',
      'equine',
      'femboy',
      'feral',
      'feral penis',
      'gag',
      'horse',
      'horsecock',
      'humiliation',
      'in public',
      'latex',
      'pony',
      'sex toy',
      'unicorn',
    ],
  },
  {
    artist: 'Wanderlustguild',
    id: 728,
    name: 'Wanderlust: Introductory Comic',
    modName: 'Inceptions',
    errorText: null,
    cat: 'Furry',
    tag: 'MF+',
    numberOfPages: 5,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: [
      'charizard',
      'cum on face',
      'cunnilingus',
      'excessive cum',
      'feral',
      'feral penis',
      'horsecock',
      'licking',
      'sex toy',
      'vaginal',
    ],
  },
  {
    artist: 'Whygena',
    id: 729,
    name: "Reggie's First Summon",
    modName: 'illmatah',
    errorText: null,
    cat: 'Furry',
    tag: 'M',
    numberOfPages: 19,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: ['anal', 'cumshot', 'femboy', 'mouse', 'tentacles'],
  },
  {
    artist: 'Kakhao',
    id: 730,
    name: 'Morph BNA',
    modName: 'illmatah',
    errorText: null,
    cat: 'Furry',
    tag: 'MF+',
    numberOfPages: 22,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: ['anal', 'blowjob', 'rimjob', 'wolf'],
  },
  {
    artist: 'Funkybun',
    id: 731,
    name: 'On Full Display',
    modName: 'illmatah',
    errorText: null,
    cat: 'Furry',
    tag: 'MF+',
    numberOfPages: 20,
    state: 'wip',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: ['exhibitionism', 'group'],
  },
  {
    artist: 'Pokilewd',
    id: 732,
    name: 'Free Drinks',
    modName: 'illmatah',
    errorText: null,
    cat: 'Furry',
    tag: 'MF',
    numberOfPages: 4,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: ['blowjob', 'femboy', 'human', 'red panda'],
  },
  {
    artist: 'Tokifuji',
    id: 733,
    name: 'Epic GAYMER Moment',
    modName: 'illmatah',
    errorText: null,
    cat: 'Furry',
    tag: 'MM',
    numberOfPages: 3,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: ['anal', 'blowjob', 'buttplug', 'chastity', 'threesome'],
  },
  {
    artist: 'Brae!',
    id: 734,
    name: 'Getting Familiar (Still exclusive, dont post)',
    modName: 'atreidae',
    errorText: null,
    cat: 'Furry',
    tag: 'MM',
    numberOfPages: 12,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: [
      'age difference',
      'anal',
      'anthro',
      'biting',
      'blowjob',
      'canine',
      'canine penis',
      'cum in ass',
      'cum inside',
      'hands free',
      'knotting',
    ],
  },
  {
    artist: 'JedaySkayVoker',
    id: 735,
    name: 'Play the Record - Chapter 4',
    modName: 'atreidae',
    errorText: null,
    cat: 'MLP',
    tag: 'MM',
    numberOfPages: 5,
    state: 'wip',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: [
      'anal',
      'bdsm',
      'bondage',
      'buttplug',
      'chastity',
      'crossdressing',
      'equine',
      'femboy',
      'feral',
      'feral penis',
      'gag',
      'horse',
      'horsecock',
      'humiliation',
      'in public',
      'latex',
      'pony',
      'sex toy',
      'unicorn',
    ],
  },
  {
    artist: 'Jackaloo',
    id: 736,
    name: 'The Gardner',
    modName: 'linxwolf',
    errorText: null,
    cat: 'Furry',
    tag: 'MM',
    numberOfPages: 14,
    state: 'wip',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: [
      'blowjob',
      'canine',
      'chubby',
      'dog',
      'in public',
      'licking',
      'masturbation',
      'outside',
    ],
  },
  {
    artist: 'Artdecade',
    id: 737,
    name: 'Palm Of My Hand',
    modName: 'linxwolf',
    errorText: null,
    cat: 'Furry',
    tag: 'MM',
    numberOfPages: 6,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: [
      'anthro',
      'blowjob',
      'cum in mouth',
      'cum on face',
      'cumshot',
      'threesome',
    ],
  },
  {
    artist: 'JedaySkayVoker',
    id: 738,
    name: 'Magical Suit',
    modName: 'atreidae',
    errorText: null,
    cat: 'MLP',
    tag: 'MM',
    numberOfPages: 5,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: ['fetish', 'gag', 'hypnosis', 'latex', 'masturbation'],
  },
  {
    artist: 'Eliana-Asato',
    id: 739,
    name: 'Friendly Rattapede Love',
    modName: 'linxwolf',
    errorText: null,
    cat: 'Furry',
    tag: 'MF+',
    numberOfPages: 6,
    state: 'finished',
    hasThumbnail: 1,
    scheduledPublish: null,
    keywords: ['anthro', 'canine', 'canine penis', 'horse', 'inflation'],
  },
];
