// Generated by Wrangler on Sun Aug 18 2024 11:36:12 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
  FRONT_END_URL_BASE: string;
  FRONT_PAGE_URL: string;
  JWT_CONFIG_STR: string;
  POSTMARK_TOKEN: string;
  DAILY_SCHEDULE_PUBLISH_COUNT: string;
  SENTRY_DSN: string;
  SENTRY_AUTH_TOKEN: string;
  CLOUDFLARE_ACCOUNT_ID: string;
  PAGES_PATH: string;
  ADS_PATH: string;
  IMAGES_SERVER_URL: string;
  DB: D1Database;
}
