// Generated by Wrangler on Sun Aug 18 2024 22:58:07 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
  FRONT_END_URL_BASE: string;
  FRONT_PAGE_URL: string;
  JWT_CONFIG_STR: string;
  POSTMARK_TOKEN: string;
  DAILY_SCHEDULE_PUBLISH_COUNT: string;
  CLOUDFLARE_ACCOUNT_ID: string;
  PAGES_PATH: string;
  ADS_PATH: string;
  IMAGES_SERVER_URL: string;
  DB: D1Database;
  CRON_KEY: string;
  GA_TRACKING_ID: string;
}
