compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]

upload_source_maps = true

[[d1_databases]]
binding = "DB"
database_name = "yiffer-dev-2"
database_id = "e9c3c06e-749e-4fe6-8934-67ce5377132e"

[[d1_databases]]
binding = "DB_PROD"
database_name = "yiffer-prod"
database_id = "b76ac518-5ce3-48ec-80cb-72e1f6f60b98"

[[r2_buckets]]
binding = "COMICS_BUCKET"
bucket_name = "yiffer-test-2"
